name: Main

on: push

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Verify MySQL connection from host
      run: |
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW DATABASES"
    - uses: actions/checkout@v2
    - name: Create database
      run: |
        scripts/setup_config.sh nemanode root password | mysql --host 127.0.0.1 --port 3306 -uroot -ppassword
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: |
        npm ci
    - name: Run tests
      run: |
        npm run test
